### ISSUE TITLE
Cannot login to the system

### ISSUE THREAD

**Issue by superlitenets** [PrakashGujarati/RadiusManager#1]
Hello bro, what is the default login username and password for the radiusmanager?

**Comment by gadhiamitul41** [comment]
Email : admin@gmail.com
Pass : secret

https://github.com/PrakashGujarati/RadiusManager/blob/master/database/seeds/AdminSeeder.php#L14

**Comment by backdoordhaka** [comment]
These credentials do not match our records.

**Comment by gadhiamitul41** [comment]
@backdoordhaka : Try /admin/login route.

**Comment by gadhiamitul41** [comment]
@backdoordhaka : Please send the URL that you use in the browser.

**Comment by backdoordhaka** [comment]
> @backdoordhaka : Please send the URL that you use in the browser.

http://172.16.1.225/login

**Comment by gadhiamitul41** [comment]
@backdoordhaka : Please try /admin/login route means 
http://172.16.1.225/admin/login (localhost/admin/login)
