### ISSUE TITLE
Login Issue.  (These credentials do not match our records.)

### ISSUE THREAD

**Issue by ghafar1280** [PrakashGujarati/RadiusManager#3]
Hi, I have installed it on my local and followed along with each step. Everything seems to be fine and working. But I am unable to login the app. 
I tried username as 'Administrator' and Password as 'secret'.  but it didnot login.
I also updated the user and password in mysql but I am unable to login.

Any help will be appriciated
Thanks and Regards.

**Comment by gadhiamitul41** [comment]
Please refer to #1
