### ISSUE TITLE
Radius issue 

### ISSUE THREAD

**Issue by ghafar1280** [PrakashGujarati/RadiusManager#4]
There is no function inside it if you help us a little bit to get the PHP file that it has give it.

**Comment by gadhiamitul41** [comment]
Can you elaborate your issue?

**Comment by ghafar1280** [comment]
Sir in this radius service not performing any function like user disable online user expire user service plan and delete option as well as dealer or payment gateway

**Comment by ghafar1280** [comment]
Can u help me .

**Comment by ghafar1280** [comment]
Thank u sir
